<?php


namespace App\Service;


use App\Repository\UserRepository;

class UserService extends UserRepository
{
    public $userRepository;

    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    public function list()
    {
        return $this->userRepository->list(); // TODO: Change the autogenerated stub
    }

    public function getById($id)
    {
        return $this->userRepository->getById($id);
    }

    public function update($request, $id)
    {
        $user =$this->getById($id);
        return $this->userRepository->update($request, $user);
    }

    public function delete($id)
    {
        $user =$this->getById($id);
        return $this->userRepository->delete($user);
    }
}
