<?php


namespace App\Service;


use App\Repository\UserRepository;

class UserService extends UserRepository
{
    public $userRepository;

    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    public function list()
    {
        return $this->userRepository->list(); // TODO: Change the autogenerated stub
    }
}
